name: Pylint

on:
  push:
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Python version
      run: python3 --version
      
    - name: Hello
      run: echo Hello World!
